import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://asgard.review.ovex.io/en/fsp');
  await page.getByLabel('FSP Hero').getByRole('link', { name: 'See Documentation' }).click();
  await page.goto('https://asgard.review.ovex.io/en/fsp');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'click here' }).click();
  const page1 = await page1Promise;
  await page.getByLabel('Our Licenses & Compliance').getByRole('link', { name: 'See Documentation' }).click();
  await page.goto('https://asgard.review.ovex.io/en/fsp');
  await page.getByLabel('Our Licenses & Compliance').getByRole('link', { name: 'See Documentation' }).click();
  await page.goto('https://asgard.review.ovex.io/en/fsp');
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'here', exact: true }).click();
  const page2 = await page2Promise;
  await page.getByLabel('Policies & Procedures').getByRole('link', { name: 'See Documentation' }).click();
  await page.goto('https://asgard.review.ovex.io/en/fsp');
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Test');
  await page.getByRole('textbox', { name: 'First Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name' }).fill('Account');
  await page.getByRole('textbox', { name: 'Last Name' }).press('Tab');
  await page.getByPlaceholder('Contact Number').fill('0123456789');
  await page.getByPlaceholder('Contact Number').press('Tab');
  await page.getByRole('textbox', { name: 'Email Address' }).fill('test@ovex.io');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.locator('.css-19bb58m').click();
  await page.getByRole('option', { name: 'Advice Given' }).click();
  await page.getByRole('textbox', { name: 'Provide detailed information' }).click();
  await page.getByRole('textbox', { name: 'Provide detailed information' }).fill('This is not to be replied to,\nThis is just a test');
  await page.getByRole('textbox', { name: 'Provide detailed information' }).press('Tab');
  await page.getByRole('textbox', { name: 'Let us know what outcome you' }).fill('No outcome to be done');
  await page.getByRole('button', { name: 'Choose a file' }).click();
  await page.getByRole('button', { name: 'Choose a file' }).setInputFiles('IMG_1678.jpeg');
  await page.getByRole('button', { name: 'Submit' }).click();
});